name: Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t appsec-ci-pipeline .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: appsec-ci-pipeline
          format: table

  zap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t https://appsec-ci-pipeline.onrender.com
